update dev.yaml

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,10 +1,9 @@
 name: Add to Exchange and Deploy to Sandbox
 
 on:
-  workflow_dispatch:
   push:
-    branches:
-      - Dev
+    tags:
+      - 'staging_blue_*' #tagの環境名を監視する
 
 env:
   APPID: ${{ secrets.mule_connected_app_sand_id }}
@@ -13,7 +12,30 @@ env:
   ENVSECRET: ${{ secrets.sandbox_client_secret }}
 
 jobs:
+  vaildatetags:
+    runs-on: ubuntu-latest
+    steps:      
+    - name: Validate tag
+      run: |
+        TAG_NAME="${GITHUB_REF##*/}"
+        echo "Tag: $TAG_NAME" 
+        # tag名のフォーマット検証
+        if [[ ! "$TAG_NAME" =~ ^staging_blue_([0-9]{8})_([0-9]{2})$ ]]; then
+          echo "ERROR: Tag must match: staging_blue_YYYYMMDD_XX (e.g. staging_blue_20250901_01)"
+          exit 1
+        fi
+        DATE_PART="${BASH_REMATCH[1]}" # 日付け
+        VERSION_PART="${BASH_REMATCH[2]}" # 連番
+        echo "Date: $DATE_PART"
+        echo "Version Number: $VERSION_PART"
+        # 日付け検証
+        if ! date -d "$DATE_PART" "+%Y%m%d" >/dev/null 2>&1; then
+          echo "ERROR: Invalid date: $DATE_PART"
+          exit 1
+        fi
+
   exchangedep:
+    needs: vaildatetags
     runs-on: ubuntu-latest
     steps:
     - name: Checkout this repo
